config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get 'tasks/today' => 'tasks#today'
  get 'tasks/week' => 'tasks#week'

  resources :tasks
  devise_for :users

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :all_tasks, only: [:index, :create, :update, :destroy]
  before_action :set_tasks, only: [:edit, :update, :destroy]
  respond_to :html, :js

  def index
    @tasks = Task.all
  
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @task = Task.new
  end
  
  def update
    @task.update_attributes(task_params)
  end

  def create
    @task  = Task.create(task_params)
  end
  
  def destroy
    @task.destroy
  end

  private

    def all_tasks
      @tasks = Task.all
    end
    
    def set_tasks
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:task, :due_date, :is_completed, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_nav.html.erb
<%= nav_bar brand: "Taskech", responsive: true do %>
  <%= menu_group do %>
    <%= drop_down "Tasks" do %>
      <%= menu_item "All Tasks", tasks_path %>
      <%= drop_down_divider %>
      <%= menu_item "Today's Tasks", tasks_today_path %>
      <%= menu_item "Week's Tasks", tasks_week_path %>
    <% end %>
  <% end %>
  <%= menu_group pull: :right do %>
    <% if current_user %>
      <%= menu_item "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= menu_item "Sign in", new_user_session_path %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Workspace" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    
    <%= render "layouts/nav" %>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/home.html.erb
<h1>Taskech Landing Page</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/tasks/_form.html.erb
<%= form_for @task, :html => { :class => "form-horizontal task" }, remote: true do |f| %>

  <% if @task.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :task, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :task, :class => 'form-control' %>
    </div>
    <%=f.error_span(:task) %>
  </div>
  <div class="form-group">
    <%= f.label :due_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :due_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:due_date) %>
  </div>
  <div class="form-group">
    <%= f.label :is_completed, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :is_completed, :class => 'form-control' %>
    </div>
    <%=f.error_span(:is_completed) %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tasks_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/tasks/_task.html.erb
<tr>
  <td><%= link_to task.id, task_path(task) %></td>
  <td><%= task.task %></td>
  <td><%= task.due_date %></td>
  <td><%= task.is_completed %></td>
  <td><%= task.user_id %></td>
  <td><%=l task.created_at %></td>
  <td>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
          edit_task_path(task), :class => 'btn btn-default btn-xs', remote: true %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
          task_path(task),
          :method => :delete,
          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
          :class => 'btn btn-xs btn-danger', remote: true %>
  </td>
</tr>

app/views/tasks/create.js.erb
$('#tasks').html("<%= j (render @tasks) %>");
$('#task-form').slideUp(350);

app/views/tasks/destroy.js.erb
$('#tasks').html("<%= j (render @tasks) %>");

app/views/tasks/edit.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

app/views/tasks/index.html.erb
<%- model_class = Task -%>
<div class="row">
  <div class="col-md-4 col-md-offset-1">
    <h2>My Tasks</h2>
  </div>

  <div class="col-md-2">
    <%= link_to new_task_path, remote: true do %>
      <button class="btn btn-default">New</button>
    <% end %>
  </div>
</div>


<div class="row">
  <div class="col-md-6 col-md-offset-2" id="task-form" style="display:none;"></div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:task) %></th>
      <th><%= model_class.human_attribute_name(:due_date) %></th>
      <th><%= model_class.human_attribute_name(:is_completed) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody id="tasks">
    <%= render @tasks %>
  </tbody>
</table>

app/views/tasks/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

app/views/tasks/today.html.erb
<h1>Tasks for Today</h1>

app/views/tasks/update.js.erb
$('#tasks').html("<%= j (render @tasks) %>");
$('#task-form').slideUp(350);

app/views/tasks/week.html.erb
<h1>Tasks for this Week</h1>